### ISSUE TITLE
Series: Add episodes-view

### ISSUE THREAD

**Issue by neufeind** [Alcidauk/CineLog#13]
For a series it would be great to be able to view descriptions of each episode, and to chech-mark those you have already viewed to keep track. I use similar apps for that task currently, which also rely on tmdb to fetch episode-data. And there episodes are sorted in seasons.

**Comment by Alcidauk** [comment]
Hi,

I have already been thinking of the season and episode support in this app, and I hope to do it when I will have time to do it.

But I think it will be a big feature, so I can't promise to release it in the near future. When you say similar app, what app is this ? And what feature Cinelog gives you that you can't find in other apps you're using ?

I just ask it to know what should do Cinelog to be useful. The first purpose of this app is to save reviews of films and series and I wonder if it is a good idea to develop features that are a little bit far of this first goal.

In any case, thanks for this suggestion !

**Comment by Tvax** [comment]
CineLog should implements everything DroidShows does, and that would be awesome !

**Comment by neufeind** [comment]
@Alcidauk For series with seasons/episodes I currently work with both apps "Episodes" and "SeriesGuide", of which I like "SeriesGuide" best. But they only offer series and not movies. I used other tools (Kinolog and Movie DB) for movies, but they don't support series. And with most of those apps things like backups/sync of the list of entries are a pain, thing like the UI could be improved here or there. That's why I went looking for alternatives. Cinelog seems nice, well supported and aims to support both movies as well as series. That's why I thought episodes-support might be a must, so you can keep track of how much of a series you already watched etc.
@Tvax: I'll give DroidShows a try as well :-)

**Comment by cpfree29** [comment]
@Alcidauk although the first purpose of this app is to save reviews of films and series, there is nothing wrong if you add more functions. More useful functions means that you will cover most users. If you ask me personaly, i don't want to use different app for movies, different for series, different for anime. Who would like that? So it would be ideal if you could cover the best you can all users. Of course you will need time and put effort to this, but maybe you can do it and then you will have one of the best apps if not the best.

Right now i am using Hobi for tv series, CineTrak for movies (although it covers series also but i am not pleased with it) and MALClient for anime, because it shows episodes like 506, 786, 843 etc. and i always want to know for example that episode 4 from season 6 is the 442 episode. You know what i mean right? Episode view would be great!

@Tvax If i remember correctly DroidShows offers plenty options, but i was not happy with import export. Something was going wrong with the process, it was mixing the pictures of tv shows after import. Now it looks abandoned.

**Comment by Alcidauk** [comment]
Hi everyone,

I started integrating an episode view. It will be included in the next release (1.3.0). As of now, it just shows episodes. 
But the final goal is to allow you to store the viewing of the episode. This will be the next feature.

**Comment by Alcidauk** [comment]
Hi,

I forgot to keep you up to date with this feature: you can store episode's viewing for a while now ;-) 

Although it was implemented, I just fixed a bug with the save of viewing. The next release will include this bugfix. 

I close this issue !
